build:
  uri: https://github.com/wildfly-extras/first-responder-demo
  ref: main
  contextDir: backend
  mode: s2i
  env:
      - name: MAVEN_ARGS_APPEND
        value: "-DskipTests -DfailOnMissingWebXml=false -Dquarkus.container-image.push=false"
      - name: POSTGRESQL_DRIVER_VERSION
        value: '42.5.0'
  s2i:
    featurePacks:
      - org.jboss.eap:eap-datasources-galleon-pack:7.4.0.GA-redhat-00003
    galleonLayers:
      - cloud-server
      - postgresql-datasource
      - microprofile-reactive-messaging-kafka
deploy:
  env:
    # Env vars to connect to PostgreSQL DB
    - name: POSTGRESQL_DATABASE
      value: frdemo
    - name: POSTGRESQL_USER
      value: frdemo
    - name: POSTGRESQL_PASSWORD
      value: frdemo
    - name: POSTGRESQL_DATASOURCE
      value: FRDemoDS
    - name: POSTGRESQL_JNDI
      value: java:/FRDemoDS
    - name: POSTGRESQL_SERVICE_HOST
      value: frdemo-ds
    - name: POSTGRESQL_SERVICE_PORT
      value: "5432"
    - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
      value: frdemo-kafka:9092
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 100
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frdemo
  containers:
    - resources:
        requests:
          cpu: 100m
          memory: 500Mi
